### ISSUE TITLE
Add spacing between navigation bar and main content of cohort pages

### ISSUE THREAD

**Issue by Idadelveloper** [unicef/inventory#100]
# Summary

The navigation bar seems to be overlapping with the main content of all the cohort pages (https://unicef.github.io/inventory/cohorts/)

## What you expected to happen

There is supposed to be some spacing between the navbar and main content like [here](https://unicef.github.io/inventory/communities/fedora/) for example.

**Screenshots**:

![cohort-page](https://user-images.githubusercontent.com/56026636/144091307-d5281e5c-f343-4306-9244-a3a770cad9c9.png)

**Comment by jwflory** [comment]
Added to the project board for this sprint.
