### ISSUE TITLE
Final internship sprint for Ida (Weeks 24-25)

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory#115]
# Summary

Create onboarding guidance for future interns or volunteers who would work on the UNICEF Open Source Inventory and/or the UNICEF Inventory Hugo theme.

# Background

In the past few months, the Open Source Inventory has come a long way! The Team Profiles feature [debuted](https://github.com/unicef/inventory/pull/78) and several start-ups are [already featured](https://unicef.github.io/inventory/cohorts/) on the Open Source Inventory. Many other needed improvements were made, like [breadcrumb navigation](https://github.com/unicef/inventory-hugo-theme/pull/5), compliance with [UNICEF](https://github.com/unicef/inventory-hugo-theme/pull/25) [brand](https://github.com/unicef/inventory-hugo-theme/pull/6) [and](https://github.com/unicef/inventory-hugo-theme/pull/21) [identity](https://github.com/unicef/inventory-hugo-theme/pull/22) [requirements](https://github.com/unicef/inventory/pull/76), adding a [banner announcement feature](https://github.com/unicef/inventory-hugo-theme/pull/10), and [several](https://github.com/unicef/inventory-hugo-theme/pull/7) [improvements](https://github.com/unicef/inventory-hugo-theme/pull/2) to overall user experience. We also helped [support the launch](https://github.com/unicef/inventory-hugo-theme/pull/11) of another site using the same theme, the [UNICEF Drones for Sustainable Development Goals Toolkit](https://unicef.github.io/drone-4sdgtoolkit/). Another site, the [Sustain OSS Design & UX portal](https://sustainers.github.io/design/), is prototyping using the same theme.

Now that we are here and looking back on all that was accomplished these past few months, this is a good time to pause and reflect. We can look back on what worked well and what didn't. What things could be better documented or explained? What new features could use documentation? We can focus on the newcomer experience to make it easier for others who come after.

# Details

The objective is to create onboarding guidance for new contributors or future interns. This could exist as a new page in the [Meta -> Open Source Inventory category](https://unicef.github.io/inventory/meta/inventory/) on the Inventory. The new contributor on-boarding guidance could cover topics like the following:

* Basic concepts about the project
* Learning about Hugo
* "Feature profiles" A.K.A. a detailed overview of a more complex feature of the Inventory theme and how it works
* Places to get help when stuck
* What the development workflow is like
* How to know what to work on? (Or, how does the GitHub project board work?)
* Tips and tricks for working on the Inventory theme
* Anything you wish you knew about earlier than you did

## Pending review before end of sprint

Outside of the onboarding guide, this section is to keep track of any remaining issues or Pull Requests to close out with @Idadelveloper (also see [_this milestone tracker_](https://github.com/unicef/inventory-hugo-theme/milestone/1)):

- [x] ~~**PR Review**: https://github.com/unicef/inventory-hugo-theme/pull/39~~
- [x] ~~**PR Review**: https://github.com/unicef/inventory-hugo-theme/pull/40~~
- [x] ~~**Change under review**: https://github.com/unicef/inventory-hugo-theme/pull/45~~
- [x] ~~**Bug fix**: https://github.com/unicef/inventory-hugo-theme/issues/36~~
- [x] **Change under review**: https://github.com/unicef/inventory/pull/110

# Outcome

A better experience for others who come after when working on the UNICEF Open Source Inventory and the UNICEF Inventory Hugo theme, and a kudos to @Idadelveloper's great work the past few months to improve the site. :tada:

**Comment by jwflory** [comment]
Thanks @Idadelveloper for all your hard work over the last many months! We are going to miss you in the Office of Innovation. All the best on what comes next. 🚀

**Comment by Idadelveloper** [comment]
@jwflory thanks too for all the support.
