### ISSUE TITLE
Migrate Data Ethics & Transparency category to Data Science Toolkit

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory#128]
# Summary

Migrate the _Data Ethics & Transparency_ category in the Open Source Inventory into the [_Data Science & AI Toolkit_](https://github.com/unicef/ooi-toolkit-ds).

# Background

@dalvarez83 is leading as our Data Science & AI Mentor at the [Venture Fund](https://www.unicefinnovationfund.org/), where we are also leading on creating new toolkits to support Venture Fund open source start-ups. The _Data Ethics & Transparency_ category on this site was always a unique topic on the Open Source Inventory and had great content originally written by @Nolski during his time at UNICEF. It makes a natural fit in the Data Science & AI Toolkit to be published along with other contextually-relevant data. So, let's move this content there.

# Details

1. Copy `content/data/` from `unicef/inventory` and add it as `content/privacy-ethics` to `unicef/ooi-toolkit-data`
2. Rename category in `_index.en` to `Data Privacy & Ethics`
3. Submit a Pull Request to `unicef/ooi-toolkit-data`.

_Note_: We don't want to remove it from `unicef/inventory` yet. We want to redirect the URLs to the new location to preserve historical links. But this will require some improvisation for linking across different Hugo sites. We'll think through this challenge in a different issue.

# Outcome

_Data Ethics & Transparency_ content in Open Source Inventory is given better visibility as a building block of the Data Science & AI Toolkit.

**Comment by barcha47** [comment]
Hey @jwflory , i can't find **unicef/ooi-toolkit-data** repositery?

**Comment by dalvarez83** [comment]
@jwflory @barcha47 It should be the content located [here](https://github.com/unicef/inventory/tree/main/content/data)

**Comment by barcha47** [comment]
@dalvarez83  thats the source repo you mentioned , i was looking for desitnation repo : ** unicef/ooi-toolkit-data**

**Comment by barcha47** [comment]
hey @jwflory  I would like work on this issue.

**Comment by dalvarez83** [comment]
@jwflory @barcha47 I think you are referring to [ooi-toolkit-ds](https://github.com/unicef/ooi-toolkit-ds)/[content](https://github.com/unicef/ooi-toolkit-ds/tree/main/content)

**Comment by jwflory** [comment]
Hi @barcha47, this issue is not ready for contribution. For the Outreachy contribution period, the [theme issue tracker](https://github.com/unicef/inventory-hugo-theme/issues) is the best place to look for new tasks.

I would also like to note that I [closed the project for new applicants](https://www.outreachy.org/communities/cfp/unicef/) in the Outreachy portal. It is a very competitive round and we only have one funded internship. It may be strategic to look at other communities with fewer applicants for their mentored projects. I know the [Fedora Project](https://www.outreachy.org/communities/cfp/fedora/) is one other excellent community and they are funding three interns.
