### ISSUE TITLE
[HUGO] Make blockquotes more pretty and make citation more clear

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory#14]
# Summary

Blockquote text renders in a way that I find difficult to read; it should be made prettier and clearly make an attribution.

# Background

**Is your improvement related to a problem? Please describe**:

Blockquotes are not aesthetically pleasing to me. It only adds a gray background, and the blockquote citation appears outside the gray area.

![Screenshot from "GPLv2 vs. GPLv3" article and an example of a blockquote](https://user-images.githubusercontent.com/4721034/115874828-93bdfb00-a412-11eb-904c-e47a05bd4333.png "Screenshot from GPLv2 vs. GPLv3 article and an example of a blockquote")

**Describe the solution you'd like**:

The design cue to focus on is making it very clear that the text is a quote from an individual or third-party, and not from UNICEF. There are many experts who have contributed content to this site, and it is important to clearly attribute quotes and excerpts from others.

**Describe alternatives you've considered**:

Do nothing. Use the existing blockquote. This works, but… it triggers my OCD.

# Details

There is some key information/aesthetics I would like to use:

1. **Big quotes**: The blockquote could begin with a big double-quote (`"`) to cue the reader that they are reading a quote
2. **Pictures/image**: Adding a way to _optionally_ display an image inside of a blockquote would be nice. In the above example, I'd like to include a small thumbnail of Bradley Kuhn next to the quote. But, I might not have a picture every time so it should work whether I have a picture or not.
3. **Better attribution**: The quote attribution sits outside of the gray background used for the quote now. It would be good to tie the attribution part of the UX into the rest of the blockquote.

# Outcome

Blockquotes are aesthetically pleasing, match the look-and-feel of the site, and can be personalized with an image.

**Comment by Idadelveloper** [comment]
Hello @jwflory . Will love to try work on this. But first I tried building the site with hugo. I've cloned the repo and ran `hugo server -D` but I get this error:
```
Built in 13 ms
Error: Error building site: "/home/idadel/Desktop/Unicef/inventory/content/faq/_index.en.md:6:1": failed to extract shortcode: template for shortcode "faq" not found
```
Looks like it's coming from the faq page and I can't seem to find anything helpful online to help me with this. Any idea of what I could be possibly missing?

**Comment by jwflory** [comment]
Hi @Idadelveloper, thanks for checking this out! The issue is that you need to clone this repository with one additional **git submodule**. [Git submodules](https://git-scm.com/docs/git-submodule) are like git repos inside of a git repo. This is how we pull down the theme used in this site; it actually comes from [another git repository](https://github.com/unicef/inventory-hugo-theme)!

The "hotfix" for this solution is using the `--depth` argument with `git clone`:

```bash
git clone --depth=1 git@github.com:unicef/inventory.git
cd inventory/
git submodule update --init
```

This will set up the submodule and then `hugo serve -D` should work. Could you please try this again now that I merged #16?

**Comment by jwflory** [comment]
Alternatively, this should work without the `git submodule update --init` step:

```bash
git clone --recurse-submodules git@github.com:unicef/inventory.git
```

**Comment by Idadelveloper** [comment]
> Hi @Idadelveloper, thanks for checking this out! The issue is that you need to clone this repository with one additional **git submodule**. [Git submodules](https://git-scm.com/docs/git-submodule) are like git repos inside of a git repo. This is how we pull down the theme used in this site; it actually comes from [another git repository](https://github.com/unicef/inventory-hugo-theme)!
> 
> The "hotfix" for this solution is using the `--depth` argument with `git clone`:
> 
> ```shell
> git clone --depth=1 git@github.com:unicef/inventory.git
> cd inventory/
> git submodule update --init
> ```
> 
> This will set up the submodule and then `hugo serve -D` should work. Could you please try this again now that I merged #16?

Yes it works. Though I had to install _asciidoctor_ before running `hugo serve`

**Comment by jwflory** [comment]
@Idadelveloper Good catch, I clarified the dependencies in PR #19. You might find the new contributing guidelines helpful as well:

https://github.com/unicef/inventory/blob/main/.github/CONTRIBUTING.md

**Comment by Idadelveloper** [comment]
Hello @jwflory . So I made some changes to tackle this issue as you described above. Here is a screenshot of the result. What are your thoughts?

![img1 unicef](https://user-images.githubusercontent.com/56026636/116427445-f0b71800-a83b-11eb-830c-3bda2920207e.png)

**Comment by jwflory** [comment]
@Idadelveloper This is amazing! 💯 It looks so much better than the existing one. Some quick feedback:

1. **With an image**: I suggest first center-aligning the citation text to the image, and then balancing the whitespace between the quote text and the end of the blockquote. Basically, move the image and citation a little higher. It feels far from the quote text.
2. **Without an image**: A little more whitespace between the quote text and citation. It feels a little tight.

It is unclear to me if the third screenshot is from the existing site, or if this is included in the change.

Also, a quick clarifying question. Is this with CSS/JavaScript changes in the browser, or did you get this working with the Hugo theme already? Not a problem either way, just curious.

**Comment by Idadelveloper** [comment]
@jwflory regarding the 3rd screenshot all I did was change the background colour. The changes were in the the hugo theme...had to play around with some CSS.

**Comment by jwflory** [comment]
@Idadelveloper OK, got it. I actually like using a background color that distinguishes the blockquote from the rest of the page contents. Since blockquotes are not used too heavily across pages, we can use extra emphasis with them.

**Comment by Idadelveloper** [comment]
@jwflory  so is this background color okay?

**Comment by jwflory** [comment]
Yes! I like it.

**Comment by jwflory** [comment]
#23 is merged! Closing this issue as complete. Thanks @Idadelveloper for taking this one up! 🎉 

Closing. 🌊
