### ISSUE TITLE
[CONTENT] Add OpenDesign resource from Eriol Fox/Ushahidi

### ISSUE THREAD

**Issue by Nolski** [unicef/inventory#3]
When building open source design communities, the Ushahidi project has a repository which has some useful information pertaining to open source design.

https://github.com/ushahidi/opendesign

**Comment by jwflory** [comment]
@Nolski Great idea. Recently I heard @Erioldoesdesign may be exploring ways to continue this work in a new home. Nothing is set yet, but I might want to pause on adding it in case the content gets re-homed somewhere else. 🙂

**Comment by Erioldoesdesign** [comment]
I forked this repo and updated with what volunteer activity I did on this in 2020. https://github.com/Erioldoesdesign/opendesign

The funded project within Ushahidi completed in December 2019 and I'm unsure what they intend to do with the repo from their perspective. I have had the first bits of conversations on this so updates will likely be in my forked repo when they happen 😄
