### ISSUE TITLE
Explore themes for Design category and map out new content

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory#83]
# Summary

Develop a list of key themes about design in open source and map out new content fitting into those themes

# Background

In the [SustainOSS Design & UX Working Group](https://sustainoss.org/working-groups/design-and-ux/), we have been talking for a while about documenting our learnings, conversations, and experiences in a more visible medium. I offered the UNICEF O.S. Inventory as a possible home for this documentation. We made a few steps towards collecting data for this documentation, like an open form for [anyone to submit their favorite design resources](https://forms.gle/JZZGC16BAQ69cfJe6). But as we discussed today, it would help to take a step back and look at our goal and purpose with documentation, and develop some key themes we want to explore first.

By defining themes, it will be easier for us to build and map out the content we actually want to share and publish. As @Memo-Es said, we all have resources, links, guides, and more that we always try to dig up, but they can be hard to find in the moment when we need them most! So, by developing some common themes, we can use this as a framing for what content we gather and build out.

# Details

I propose these next steps:

1. @jwflory to create a first-pass list of themes based on content we have discussed in previous WG meetings and from the form submissions
2. Review list of themes in our next WG meeting (or asynchronously in this issue)
3. Map sub-topics or specific content we wish we had, or things we know of from others, that fit within the list of themes
4. Regroup on strategy for creating the content fitting into the identified themes

When we regroup, we can get more specific into answering questions like, "What article or knowledge do we want to share? Do we write it ourselves or create a list of other resources? What gaps exist in the O.S. design space that we could begin filling?"

# Outcome

Path forward on documenting and sharing our learnings becomes more clear. It becomes easier to take first steps of creating new content.

---

CC: @Erioldoesdesign @Memo-Es @Nolski @mantas @georgiamoon @RichardLitt @jeepurs

**Comment by jwflory** [comment]
Here is some of the information I already have, just to get it out and into the open. I'll circle back to this in another week or two, [after SFScon](https://www.sfscon.it/talks/understanding-the-evolution-of-foss-community/).

## Misc. resources

* [GitHub.com design contributions](https://primer.style/contribute/design): Looks like resources for GitHub employees about design guidelines and best practices for working across github?
* [Guide to getting involved in Open Source as a Designer](https://www.notion.so/erioldoesdesign/Guide-to-getting-involved-in-Open-Source-as-a-Designer-bd7a7d81e1a1429780bb6685dda777bd): Notion page written by @Erioldoesdesign some time back
* [Design + Dev rels](https://docs.google.com/document/d/1EvupsQGHB7jE7iG43uRfVhwS6PvdAeFMQKyOz1s3D3s/edit?usp=sharing): A GDoc of notes we probably took in a UX/Design WG meeting, maybe @Erioldoesdesign remembers some context on what this is.
* [Pa11y design guidelines](https://pa11y.org/contributing/designers/): A work-in-progress page of a project creating contributing guidelines for designers.
* [Design Documentation](https://vimeo.com/434779810): _Eriol joined us to share her experience on Design Documentation. Design documentation is a very important part of design as it communicates the design itself, the rationale for decisions made to both the executives and developers. Design documentation creates some level of trust and consistency for future iterations. Eriol shared insights on how how to go around design documentation and some of the best practices._
* [Miro board - Design for Good, for designers](https://miro.com/app/board/o9J_kpHm2Dg=/): Good info dump from past exercise on open source and design
* [Defaults and Customization: When Design Meets Open Source](https://simplysecure.org/blog/globaleaks-case-study/): GlobaLeaks case study with three key themes. Blog post from Simply Secure.
  * Customization
  * Accessibility and Localization
  * Brand and Trust
* [Trauma & design](https://hrcd.pubpub.org/pub/traumaanddesign/release/7): Some basic definitions key to understanding the relationship between trauma and design. by KJ Hepworth, Kat Lo, Eriol Fox, and S Mori.
* [Design Principles](https://principles.design/): An open source collection of Design Principles and methods. (an overwheeeeelming amount of content!!)


## Responses to the WG form

Timestamp | Resource name | Resource description | URL to resource | Resource classification | Submitter name
-- | -- | -- | -- | -- | --
9/10/2021 1:30:46 | Excalidraw | it's a great intuitive and attractive tool for easy imaging/chartmaking | https://excalidraw.com/ | Interactive content or app |  
10/1/2021 11:51:52 | Open Source Design Processes at Ushahidi | This documentations work at Ushahidi was funded by DIAL to improve the readability and inclusivity of Ushahidi's documentation to encourage contribution across functions and skills and documented good amounts of examples of how a design function within a moderately resourced NGO OSS org could be done. | https://docs.ushahidi.com/platform-developer-documentation/design/design-process | Walkthrough or guided content | Eriol Fox
10/1/2021 11:54:46 | Simple.org design documentation | This is the documentation effort done by the Simple.org team for their internal design team (funded) and also the designers they engage outside of their staff. They approached design volunteer contributions with a view to select 'design experts in certain medical areas' e.g. a designer that had previously worked on diabetes tools and services. This serves as a good example of documentation and processes that can be referenced when you're an OSS org looking for 'specific design insight' | https://docs.simple.org/design-1/design | Walkthrough or guided content | Eriol Fox
10/22/2021 11:05:55 | Penpot.app | Collaborative UI design prototyping and design system creation tool (alternative to Figma) | Penpot.app | Interactive content or app | Nathan B

**Comment by Erioldoesdesign** [comment]
Jumping in here with a quick list of resources that Simply Secure are building for OSS tool developers that connects to this project: https://usable.tools/blog/

#1 User testing can be fun - A short introduction and interactive guide for devs on usertesting
#2 A dev's guide to user testing - a more intensive guide and series of activities to build a usertesting function and appreciation of usertesting in OSS tool teams. This included two workshops at conferences.
#3 User testing synthesis - how to synthesise your results from usertesting into issues and actionable OSS dev work. including a webinar
#4 Designer-developer handoff - a series of recorded conversations on how devs and designers work together on OSS with transcripts
#5 Get what you want from a designer - a selection web tool to understand what you want from a designer on your project that will accept PR's to its repo to add more examples of design briefs for loss tools.

Future resource: Shape Together: Project management for open source dev teams

**Comment by jwflory** [comment]
Heard about this from @jonatoni. The [Orbit design system](https://orbit.kiwi/) from Kiwi.com is a neat example of design documentation. Bonus points for being [fully open source](https://github.com/kiwicom/orbit).

**Comment by jwflory** [comment]
Following up here. Taking a first pass at identifying common themes across these examples above, as well as identifying some next steps for where to take this work. I'm hoping to present this next Tuesday (2021 December 14) at the monthly Sustain OSS [Design & UX Working Group](https://sustainoss.org/working-groups/design-and-ux/) meeting.

## Possible themes / topics

* **Defining design**: When we say design, what exactly do we mean? What is the vocabulary behind design, its key concepts, and how this take shape in open communities? Depending on who you ask, everyone seems to have a different perception on this question, and there is probably some truth in all of these different responses. Most notably though, this is helpful to dispel the myth that "design" only means graphic design, making logos and pretty images, etc.
* **For the maintainers**: If you maintain an open source project, what steps can you take to make your project and community more inclusive and welcoming for design contributions? This theme is targeted for people who want to embrace design for their project, but do not have knowledge or experience in design. This could include activities and exercises to help a maintainer think from the perspective of a prospective design contributor to their project.
* **For the designers**: If you are a designer looking to participate in open source, what key information do you need to know in order to be successful? This theme is targeted for designers who are looking to enter open source spaces and better understand how open communities typically function. This could include advice, best practices, and/or exercises to help a designer successfully engage in an open project.
* **Guidelines & frameworks**: Best practices and resources to help "level up" design thinking in a project or community. This could be advice or best practices on how to create common design resources, frameworks, patterns, and/or templates to make design-oriented practices for commonplace in a project. This is different from the last two themes because it is somewhat more advanced. The ideal audience for this content is past the beginner level, but not quite at the expert level.
* **Case studies & examples**: Theory is great, but sometimes you _really_ just need to see it to understand it. This theme focuses on tools, design frameworks, or other examples from real-world projects and communities. The purpose of including case studies is to help someone move past that challenging step of theoretical understanding and conceptualization, to **actually doing it** in their own project or community.

## Suggested next steps

I am mapping three possible steps forward here:

1. **Build out new sub-categories in the UNICEF Inventory _Design_ category**: This is what we discussed last time. New sub-categories for each theme above would be added to the UNICEF Inventory. We can begin building out the themes by adding content underneath each sub-category.
2. **Launch a new SustainOSS design knowledgebase, using the theme from the UNICEF Inventory**: Create a new GitHub repository for this project, and make each theme its own "main" category. The site would be dedicated to "Design in Open Source" as the main focus. It could leverage the same theme (i.e. look-and-feel) of the UNICEF Inventory site, but customized for a SustainOSS context.
3. **Launch a new UNICEF design knowledgebase, using the theme from the UNICEF Inventory**: Same as item 2, but maintained under the UNICEF namespace.

I'm keen to hear feedback from folks in next Tuesday's meeting to map next steps on where to take this work forward, and also to help us make a concrete resource that brings our knowledge and expertise together!

---

CC: @Erioldoesdesign @Memo-Es @Nolski @mantas @georgiamoon @RichardLitt @jeepurs

**Comment by Erioldoesdesign** [comment]
These themes and the descriptions are *perfect* Justin!!!! 💐 

I vote we spend some time thinking about sub categories but also that we try to find 1 resource that fits each sub category or assign a person to seek an appropriate resource for each sub category.

e.g.
Big Theme: For the maintainers

Sub theme: Making a design-contributions.md 
Resource: a good example of a design-contrinbutions md file from another project and why.

etc. etc. for each sub category.

I do think it's important to consider what org this is hosted under but right now, unless there are maintainer concerns re. having it on UNICEF we can keep this on UNICEF? But also very happy for it to move under sustain design & UX WG

**Comment by georgiamoon** [comment]
Late chiming into the thread...

@jwflory does the UNICEF knowledge base have the ability to add entries from external content? 

My question re: the options of how to build this out and where would be around audience and goals. I wonder if some things should live at each location but be curated / tailored for a UNICEF vs Sustain audience in various appropriate ways?

I can't make the call tomorrow, so I just wanted to be sure to chime in with that point! What's the audience/persona for each site and how that impacts any framing/UX decisions about how to experience the content.

**Comment by jwflory** [comment]
> **_@Erioldoesdesign wrote…_**
> I vote we spend some time thinking about sub categories but also that we try to find 1 resource that fits each sub category or assign a person to seek an appropriate resource for each sub category.

This could be useful for calls to contribute in the working group too. For example, in Slack and on Discourse, if folks want to participate asynchronously outside of meetings.

> I do think it's important to consider what org this is hosted under but right now, unless there are maintainer concerns re. having it on UNICEF we can keep this on UNICEF? But also very happy for it to move under sustain design & UX WG

I have no issue hosting here. The advantage of the Inventory is it gives us somewhere to publish quickly and it is maintained as part of the Open Source Mentorship provided by the [UNICEF Innovation Fund](https://www.unicefinnovationfund.org/). One thing I am thoughtful about is that the content in this site may be reframed/regrouped into sections specific on meeting the [Digital Public Goods Standard](https://digitalpublicgoods.net/standard/). Design topics are relevant to these, but it is a different approach to how content could be organized in the future.


> **_@georgiamoon wrote…_**
> @jwflory does the UNICEF knowledge base have the ability to add entries from external content?

I think yes and no, but depends on what you are thinking of with external content. I created [list articles](https://unicef.github.io/inventory/legal-policy/reading-list/) for topics where linking out to other authors felt more useful. One feature request I've made is to offer "download portals" to other content:

https://github.com/unicef/inventory-hugo-theme/issues/34

> I can't make the call tomorrow, so I just wanted to be sure to chime in with that point! What's the audience/persona for each site and how that impacts any framing/UX decisions about how to experience the content.

Thanks for the add! They are good questions to help with framing intent and discovery of the content.

**Comment by jwflory** [comment]
Hi, as a follow-up here, the theme for the Design category are explored and a map for new content exists on the SustainOSS Design knowledge-base site. This was soft-launched in sustainers/design#3 and unicef/inventory#109. I closed this issue so the discussion can move to the issue tracker of the new project site:

https://github.com/sustainers/design/issues

I will open new issues there to guide next steps for the working group in our monthly meetings. Keeping this issue closed. 🎬
