### ISSUE TITLE
Remove TravisCI from the suggested CI platforms

### ISSUE THREAD

**Issue by iperdomo** [unicef/inventory#96]
# Summary

Travis CI has changed their offering to open source projects. And the suggested platform `travis-ci.org` is not longer available:

![2021-11-23_1238x232](https://user-images.githubusercontent.com/178474/143082225-12c88228-c969-4c46-884e-5e065983364f.png)

* https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps
* https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

I have experienced long wait times on `travis-ci.org` (before the merge), and it seems that the free tier is quite limited. Other projects have moved away from this platform.

## What you expected to happen

My suggestion is to remove TravisCI from the list of suggested CI platforms.

**Comment by jwflory** [comment]
Thanks for opening this @iperdomo. +1. I don't recommend Travis anymore for the same pricing plan reason. And also faced the long build times you mentioned. 😅 Somehow I suspect those two things are related…

I'll get a PR up today or tomorrow to drop it from the list. 👍🏻

**Comment by iperdomo** [comment]
@jwflory I can open a PR and get my first contribution to the Inventory 😄

**Comment by jwflory** [comment]
@iperdomo Go for it! 💯
