### ISSUE TITLE
Wrap text description of profile cards around logo

### ISSUE THREAD

**Issue by Idadelveloper** [unicef/inventory#98]
# Summary

Wrap the text descriptions of the team profile cards around the logo to get rid of redundant space. When the number of characters of the short description increases, the spacing beneath the logo increases as well. It will be better if part of the text is wrapped around the image to give the cards a better look.

**Screenshots**:

![globaleaf](https://user-images.githubusercontent.com/56026636/144086323-db570b27-9835-4ae3-ae66-41eaa9307b21.png)

# Other details
This change should be made in https://github.com/unicef/inventory/blob/main/layouts/partials/cohorts.html

**Comment by jwflory** [comment]
Added to the project board for this sprint.
